services:
  - type: web
    name: refining-fire-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
